name: release

on:
  push:
    branches: [ main, dev ]


jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload All
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-All
          path: dist/*
  
      - name: Upload nowin_darwin_amd64_v1
        uses: actions/upload-artifact@v3
        with:
          name: nowin_darwin_amd64_v1
          path: dist/nowin_darwin_amd64_v1/*
  
      - name: Upload nowin_darwin_arm64
        uses: actions/upload-artifact@v3
        with:
          name: nowin_darwin_arm64
          path: dist/nowin_darwin_arm64/*
  
      - name: Upload nowin_linux_386
        uses: actions/upload-artifact@v3
        with:
          name: nowin_linux_386
          path: dist/nowin_linux_386/*
  
      - name: Upload nowin_linux_amd64_v1
        uses: actions/upload-artifact@v3
        with:
          name: nowin_linux_amd64_v1
          path: dist/nowin_linux_amd64_v1/*
  
      - name: Upload nowin_linux_arm_7
        uses: actions/upload-artifact@v3
        with:
          name: nowin_linux_arm_7
          path: dist/nowin_linux_arm_7/*
  
      - name: Upload nowin_linux_arm64
        uses: actions/upload-artifact@v3
        with:
          name: nowin_linux_arm64
          path: dist/nowin_linux_arm64/*
  
      - name: Upload win_windows_386
        uses: actions/upload-artifact@v3
        with:
          name: win_windows_386
          path: dist/win_windows_386/*
  
      - name: Upload win_windows_amd64_v1
        uses: actions/upload-artifact@v3
        with:
          name: win_windows_amd64_v1
          path: dist/win_windows_amd64_v1/*
  
      - name: Upload win_windows_arm_7
        uses: actions/upload-artifact@v3
        with:
          name: win_windows_arm_7
          path: dist/win_windows_arm_7/*
  
      - name: Upload win_windows_arm64
        uses: actions/upload-artifact@v3
        with:
          name: win_windows_arm64
          path: dist/win_windows_arm64/*

      #- name: Checkout Dist
      #  uses: actions/checkout@v2
      #  with:
      #    repository: 'gocq/dist'
      #    ref: master
      #    ssh-key: ${{ secrets.SSH_KEY }}
      #    path: upstream/dist

      #- name: Update Dist
      #  run: |
      #    chmod +x scripts/upload_dist.sh
      #    ./scripts/upload_dist.sh
